// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtUwAP6G2kHOp-DsPrPLi-AYeqGwxlMOU',
    appId: '1:330197979201:web:12b2dfc49d2f3ad55936c0',
    messagingSenderId: '330197979201',
    projectId: 'piacademy-app',
    authDomain: 'piacademy-app.firebaseapp.com',
    storageBucket: 'piacademy-app.firebasestorage.app',
    measurementId: 'G-01547Y909N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsx3IHkQMrLWniU6hUM_ffc6i7s02nt6o',
    appId: '1:330197979201:android:6155e706d89265195936c0',
    messagingSenderId: '330197979201',
    projectId: 'piacademy-app',
    storageBucket: 'piacademy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUObSyKesIUdiyk7VAEhnaF8nDfas41ho',
    appId: '1:330197979201:ios:e2174c6ccd1114725936c0',
    messagingSenderId: '330197979201',
    projectId: 'piacademy-app',
    storageBucket: 'piacademy-app.firebasestorage.app',
    iosBundleId: 'com.example.piacademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUObSyKesIUdiyk7VAEhnaF8nDfas41ho',
    appId: '1:330197979201:ios:e2174c6ccd1114725936c0',
    messagingSenderId: '330197979201',
    projectId: 'piacademy-app',
    storageBucket: 'piacademy-app.firebasestorage.app',
    iosBundleId: 'com.example.piacademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtUwAP6G2kHOp-DsPrPLi-AYeqGwxlMOU',
    appId: '1:330197979201:web:1a4a9458bb4fab405936c0',
    messagingSenderId: '330197979201',
    projectId: 'piacademy-app',
    authDomain: 'piacademy-app.firebaseapp.com',
    storageBucket: 'piacademy-app.firebasestorage.app',
    measurementId: 'G-ZGZ9LHJHZZ',
  );
}
